services:
  mermaid:
    build:
      target: mermaid-dev
    entrypoint:
      - pnpm
      - exec
      - vite
      - dev
      - --host
      - 0.0.0.0
      - --port
      - "8080"
    volumes:
      - ./src:/app/src
    ports:
      - 24678:24678
