version: '3.7'
services:
  mermaid:
    build:
      context: .
      target: mermaid-dev
    volumes:
      - ./src:/app/src
    ports:
      - "${PORT_WEB:-3000}:3000"
      - "${PORT_PRIVATE:-24678}:24678"
    networks:
      - ben
networks:
  ben:
    external: true