[build.environment]
	MERMAID_ANALYTICS_URL = 'https://p.mermaid.live'
	MERMAID_DOMAIN = 'mermaid.live'
	MERMAID_RENDERER_URL = 'https://mermaid.ink'
	MERMAID_KROKI_RENDERER_URL = 'https://kroki.io'
	MERMAID_IS_ENABLED_MERMAID_CHART_LINKS ='true'

[[redirects]]
  from = "/index.html"
  to = "/edit"
  status = 301
  force = true
