name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 0 * * 4'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          exempt-issue-labels: 'retained'
          exempt-pr-labels: 'retained'
          stale-issue-message: 'This issue is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 14 days'
          stale-pr-message: 'This pr is stale because it has been open 90 days with no activity. Remove stale label or comment or this will be closed in 14 days'
          days-before-stale: 90
          days-before-close: 14
          days-before-pr-close: -1
